[brick]
name = "Parquet"
version = "0.2.0"
type = "library"
chplVersion = "2.8.0"
source = "https://github.com/chapel-lang/Parquet"
authors = ["Engin Kayraklioglu", "Shreyas Khandekar", "Ben Harshbarger"]
license = "Apache-2.0"
copyrightYear = "2026"

[dependencies]
[system]
arrow = "25.0.0"
parquet = "25.0.0"
